#!/usr/bin/env bash
git clone https://github.com/apache/camel.git
git clone https://github.com/apache/hbase.git
git clone https://github.com/apache/hive.git
git clone https://github.com/apache/commons-codec.git
git clone https://github.com/apache/commons-collections.git
git clone https://github.com/apache/commons-compress.git
git clone https://github.com/apache/commons-configuration.git
git clone https://github.com/apache/commons-crypto.git
git clone https://github.com/apache/commons-csv.git
git clone https://github.com/apache/commons-io.git
git clone https://github.com/apache/commons-lang.git
git clone https://github.com/apache/commons-math.git
git clone https://github.com/apache/commons-weaver.git
git clone https://github.com/jboss-fuse/fuse.git
git clone https://github.com/jboss/metadata.git
git clone https://github.com/wildfly-security/wildfly-elytron.git
git clone https://github.com/wildfly-swarm/wildfly-swarm.git
git clone https://github.com/wildfly/wildfly-arquillian.git
git clone https://github.com/wildfly/wildfly-core.git
git clone https://github.com/wildfly/wildfly.git
git clone https://github.com/wildfly/wildfly-maven-plugin.git
git clone https://github.com/spring-projects/spring-amqp
git clone https://github.com/spring-projects/spring-android
git clone https://github.com/spring-projects/spring-batch
git clone https://github.com/spring-projects/spring-batch-admin
git clone https://github.com/spring-projects/spring-data-commons
git clone https://github.com/spring-projects/spring-data-neo4j
git clone https://github.com/spring-projects/spring-data-jpa
git clone https://github.com/spring-projects/spring-data-mongodb
git clone https://github.com/spring-projects/spring-data-redis
git clone https://github.com/spring-projects/spring-data-rest
git clone https://github.com/spring-projects/spring-ldap
git clone https://github.com/spring-projects/spring-mobile
git clone https://github.com/spring-projects/spring-roo
git clone https://github.com/spring-projects/spring-security
git clone https://github.com/spring-projects/spring-security-oauth
git clone https://github.com/spring-projects/spring-data-gemfire
git clone https://github.com/spring-projects/spring-hadoop
git clone https://github.com/spring-projects/spring-shell
git clone https://github.com/spring-projects/spring-social
git clone https://github.com/spring-projects/spring-social-facebook
git clone https://github.com/spring-projects/spring-social-linkedin
git clone https://github.com/spring-projects/spring-social-twitter
git clone https://github.com/spring-projects/spring-framework
git clone https://github.com/spring-projects/spring-webflow
git clone https://github.com/spring-projects/spring-ws
